### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by kychua** [CS2103AUG2016-T11-C4/main#101]
# Developer Guide
- Make sure sequence diagrams are drawn correctly: arrows should point to/from the top & bottom of the activation bars (refer to original diagram/handouts)
- Sequence diagram is showing interaction between all the components rather than within `Logic`
- Testing section mentions `UrlUtilTest` that's not in the code?
- Suggested additions: Can explain other interesting design decisions you made (if any)
# User Guide
- Nice to see add command is simplified, would be good if the other commands can be simplified as well (esp. commands like `fin` which will be used a lot...)
- Seems quite repetitive e.g. "Keywords like tdy, tmr, yst, are allowed in the date field." -> isn't this in the accepted date/time formats? why mention under add deadine tasks?
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command
- UI can be improved/screenshots should be updated: e.g. how are completed tasks displayed? can location be displayed in a better format? any feedback to users?

**Comment by pyokagan** [comment]
@kychua DeveloperGuide has been updated with corrected (?) sequence diagrams and a lot more implementation details.

**Comment by kychua** [comment]
- Sequence diagram arrows are correct now, but the event deletion diagram looks like it's meant to show the overall flow (all the components), so it doesn't really seem to belong in the Logic component. The developer guide should have different levels (overview -> specific), and the content should be at the appropriate level of detail (e.g. specific details that are not needed for overall understanding shouldn't be mentioned in the overview). Fig 2.5 (placed under Logic component) seems to be mixing overview and Logic component, compared to the original sequence diagram which mainly shows the parts relevant to Logic:
  ![](https://raw.githubusercontent.com/nus-cs2103-AY1617S1/addressbook-level4/master/docs/images/DeletePersonSdForLogic.png)
- Nice to see you've added details! Seems a little confusing/repetitive to have the component information in 2 separate parts with repeated content though (e.g. Model implementation seems to repeat what was mentioned in the Logic component class diagram even though the diagram is easier to understand)
- Model implementation mentions `Config` class but diagrams don't seem to mention it

Other possible additions:
- Compare with other alternative designs possible.
- Add more descriptions e.g. show at least one interaction (i.e. sequence diagrams) within each component
- Use object diagrams to show the object structure at runtime
- Use activity diagrams and OO domain models where applicable

**Comment by kychua** [comment]
Remember to update `About Us` as well
