### ISSUE TITLE
docs: Refine command format

### ISSUE THREAD

**Issue by nightism** [CS2103AUG2016-T11-C4/main#12]
- [x] Add more description for `help`
- [x] Refine `add` command into one
- [x] Refine `edit` command into one
- [x] Change `srch` to `find` or `search`
- [x] Add simple explanation for each example command
- [x] Overdue task should not be marked as finished
- [x] convert between tasks of different types (not useful at all)

**Comment by pyokagan** [comment]
- Need a way to convert between tasks of different types (e.g. `floating <-> deadline`)

**Comment by pyokagan** [comment]
@nightism What's the status of this issue?

**Comment by pyokagan** [comment]
@nightism Not all issues raised in #39 have been resolved yet.

**Comment by pyokagan** [comment]
@nightism You still need to reply to all my comments in #39 and resolve my concerns (plus any other team members', if they decide to join in)
