### ISSUE TITLE
docs: Refine Ui design

### ISSUE THREAD

**Issue by nightism** [CS2103AUG2016-T11-C4/main#13]
- Design a "Plan B" for backup

**Comment by pyokagan** [comment]
@potatowagon What's the status of this issue?

**Comment by nightism** [comment]
@pyokagan before you start this work please have a look of the new command formats and update the Quick Start session in UserGuide

**Comment by nightism** [comment]
@potatowagon before you start this work please have a look of the new command formats and update the Quick Start session in UserGuide
