### ISSUE TITLE
Archive command

### ISSUE THREAD

**Issue by pyokagan** [CS2103AUG2016-T11-C4/main#131]
This command should automatically delete all events, deadlines and floating tasks that are complete. (For events, even though they are not explicitly "completed", they are counted as finished when they are in the past).

**Comment by nightism** [comment]
> ... delete all events, ....

Meaning literally delete? Or archive in another file?

**Comment by pyokagan** [comment]
Either delete, or archive in another file (as backup). Depends on how much code you want to write.

The "archive" in another file approach will likely require us to modify the `Storage` component interface, which will be more work.

**Comment by pyokagan** [comment]
Maybe the `clear` command can be extended to take a filter e.g. `clear fin` to clear all finished tasks...
