### ISSUE TITLE
A more helpful `help`

### ISSUE THREAD

**Issue by pyokagan** [CS2103AUG2016-T11-C4/main#148]
- "help" command should not show the AddressBook-Level4 website. It should show our user guide. In fact, it is better if the help command can be accessed offline.
- `help COMMAND` will open the help window and jump to the command usage of `COMMAND`.

**Comment by pyokagan** [comment]
@snehasp13 Try to do this first.

**Comment by pyokagan** [comment]
@potatowagon Can help do this?

**Comment by potatowagon** [comment]
ok
