### ISSUE TITLE
freshly pulled master will not compile

### ISSUE THREAD

**Issue by potatowagon** [CS2103AUG2016-T11-C4/main#168]

**Comment by potatowagon** [comment]
![screenshot 58](https://cloud.githubusercontent.com/assets/19604232/19945975/718cdf3e-a17d-11e6-8a30-3a0f06f834a6.png)

**Comment by pyokagan** [comment]
@potatowagon `Refresh Gradle Project`

**Comment by pyokagan** [comment]
>  freshly pulled master will not compile 

Travis disagrees though

![mastercanr](https://cloud.githubusercontent.com/assets/109479/19950619/8e4ea4f2-a193-11e6-9eb6-3d8c2419b4cf.png)

**Comment by potatowagon** [comment]
my bad
