### ISSUE TITLE
can 00 in time input format be omitted? 

### ISSUE THREAD

**Issue by potatowagon** [CS2103AUG2016-T11-C4/main#50]
Sorry for asking this again, cant find where  i left this question. Is eg. 8pm instead of 8:00pm supported / going to be supoorted soon by parser?

**Comment by pyokagan** [comment]
As seen on [this line](https://github.com/CS2103AUG2016-T11-C4/main/blob/master/src/test/java/seedu/address/logic/parser/TimeParserTest.java#L35), it already does.

**Comment by potatowagon** [comment]
ok thanks! i see theres a 1.23 pm. so we accept `:` and `.`?

**Comment by pyokagan** [comment]
> so we accept `:` and `.`?

Yes

**Comment by potatowagon** [comment]
ok i shall update the user guiade as such

**Comment by potatowagon** [comment]
the main in master c
