### ISSUE TITLE
UI display date as 12 Dec 2016 or 12/12/2016?

### ISSUE THREAD

**Issue by potatowagon** [CS2103AUG2016-T11-C4/main#52]
Cant test on the actual UI as the UI on team master doesnt have the updated ui version.

**Comment by pyokagan** [comment]
The [Development Workflow](https://docs.google.com/document/d/1RXL5QTGgKsxaBht4rvrT9CU31sPneAR4rWAoj0Rb3yc/edit) doc shows you how you can checkout PRs on your computer. (Look for "Test the PR on your computer")

But anyway, it's something like `2016-10-10T4:00` right now.

**Comment by pyokagan** [comment]
Yeah, I'll merge #37 into master soonish. Just waiting to see if @nightism will pop up with a PR to implement deadlines or @snehasp13 pops up with a PR to implement floating tasks.

**Comment by pyokagan** [comment]
> But anyway, it's something like `2016-10-10T4:00` right now.

I think you can just come up with your own display format. We will likely be changing it very soon to be more user friendly after `v0.2` anyway. #37 focuses more on getting the data structures right first, rather than the user interface design.

**Comment by potatowagon** [comment]
oh ok thanks!
