### ISSUE TITLE
UserGuide: remove `TASK_UNIQUE_INDEX`

### ISSUE THREAD

**Issue by pyokagan** [CS2103AUG2016-T11-C4/main#66]
After thinking about it, I'm strongly against a `TASK_UNIQUE_INDEX`, for the reasons that I outlined in #39.

The index to be used in commands should just be whatever is displayed in the UI.

The UserGuide needs to be updated to remove all mentions of a `TASK_UNIQUE_INDEX`.

**Comment by potatowagon** [comment]
oh just saw this, will work on it
