### ISSUE TITLE
T8A3 feedback

### ISSUE THREAD

**Issue by kychua** [CS2103AUG2016-T11-C4/main#69]
## User stories

Mark done, edit, undo etc should be high priority since they're must-have features.
## Use cases

Nice to see comprehensive extensions! Note that UI details (e.g. colored circle for `add priority tags`, how a user adds event to group activity, input format) should not be included. Use cases come before UI design.
## NFRs

Point 3 sounds like a functional requirement. Also, in case you missed it, our module handbook specifies a number of project constraints (e.g. No Relational Databases). At least hyperlink to that document.
## Product survey

Good job with the analysis:) Very detailed!

**Comment by pyokagan** [comment]
@kychua Thanks for the feedback.
