### ISSUE TITLE
Checkstyle error issues

### ISSUE THREAD

**Issue by potatowagon** [CS2103AUG2016-T11-C4/main#82]
<img width="398" alt="why" src="https://cloud.githubusercontent.com/assets/19604232/19395210/11c86e50-926f-11e6-9c9f-26bd1646f066.PNG">

Multiple markers at this line
    - File contains tab characters (this is the first instance).
    - 'method def modifier' have incorrect indentation level 8, expected level 
     should be 4.

I dont understand the problem, how to fix this? it looks the same as the other lines of code which is okay

**Comment by pyokagan** [comment]
> it looks the same as the other lines of code which is okay

Looks can be deceiving. Try switching on [show whitespace characters](http://stackoverflow.com/a/27828467) in the editor to see the problem.

And then, [configure Eclipse to use spaces for indentation](http://stackoverflow.com/a/408449) to fix the problem.

**Comment by pyokagan** [comment]
Not really a bug, more like a question. Let's set up a new label for that...
