### ISSUE TITLE
docs: Update "About Us"

### ISSUE THREAD

**Issue by pyokagan** [CS2103AUG2016-T11-C4/main#9]
- Update names and homepages of team members in docs/AboutUs.md
- Each team member must have a photo, the area of expertise and team role

**Comment by pyokagan** [comment]
@nightism @potatowagon @snehasp13 Can you all each open a PR with your About Us information by today? (see #14)

**Comment by pyokagan** [comment]
@nightism @potatowagon @snehasp13 Deadline 2359. Assign me as the reviewer.

**Comment by nightism** [comment]
@pyokagan Hello, Paul. My class end at 8 pm today, I will do this as long as my class ends.

**Comment by pyokagan** [comment]
@potatowagon ???

**Comment by potatowagon** [comment]
clean PR about us submitted
